====== Special Operator CATCH ======

====Syntax====

\DefspecWithValues catch {//tag// \starparam{form}} {\starparam{result}}

====Arguments and Values====

//tag// - a //[[CL:Glossary:catch tag]]//; \eval.

//forms// - an //[[CL:Glossary:implicit progn]]//.

//results// - if the //forms// exit normally, the //[[CL:Glossary:value|values]]// returned by the //forms//; if a throw occurs to the //tag//, the //[[CL:Glossary:value|values]]// that are thrown.

====Description====

\specref{catch} is used as the destination of a non-local control transfer by \specref{throw}. //Tags// are used to find the \specref{catch} to which a \specref{throw} is transferring control. ''(catch 'foo ''form'')'' catches a ''(throw 'foo ''form'')'' but not a ''(throw 'bar ''form'')''.

The order of execution of \specref{catch} follows:\idxtext{order of evaluation}\idxtext{evaluation order}

\beginlist \itemitem{1.} //Tag// is evaluated. It serves as the name of the \specref{catch}.

\itemitem{2.} //Forms// are then evaluated as an implicit \specref{progn}, and the results of the last //form// are returned unless a \specref{throw} occurs.

\itemitem{3.} If a \specref{throw} occurs during the execution of one of the //forms//, control is transferred to the \specref{catch} //[[CL:Glossary:form]]// whose //tag// is **[[CL:Functions:eq]]** to the tag argument of the \specref{throw} and which is the most recently established \specref{catch} with that //tag//.

No further evaluation of //forms// occurs.

\itemitem{4.} The //tag// //[[CL:Glossary:established]]// by \specref{catch} is //[[CL:Glossary:disestablished]]// just before the results are returned.

\endlist

If during the execution of one of the //forms//, a \specref{throw} is executed whose tag is **[[CL:Functions:eq]]** to the \specref{catch} tag, then the values specified by the \specref{throw} are returned as the result of the dynamically most recently established \specref{catch} form with that tag.

The mechanism for \specref{catch} and \specref{throw} works even if \specref{throw} is not within the lexical scope of \specref{catch}. \specref{throw} must occur within the //[[CL:Glossary:dynamic extent]]// of the //[[CL:Glossary:evaluation]]// of the body of a \specref{catch} with a corresponding //tag//.

====Examples==== <blockquote> (catch 'dummy-tag 1 2 (throw 'dummy-tag 3) 4) → 3 (catch 'dummy-tag 1 2 3 4) → 4 (defun throw-back (tag) (throw tag t)) → THROW-BACK (catch 'dummy-tag (throw-back 'dummy-tag) 2) → T

;; Contrast behavior of this example with corresponding example of BLOCK. (catch 'c (flet ((c1 () (throw 'c 1))) (catch 'c (c1) (print 'unreachable)) 2)) → 2 </blockquote>

====Affected By====

None. ====Exceptional Situations==== An error of type **[[CL:Types:control-error]]** is signaled if \specref{throw} is done when there is no suitable \specref{catch} //tag//. ====See Also====

\specref{throw}, {\secref\Evaluation}

====Notes====

It is customary for //[[CL:Glossary:symbols]]// to be used as //tags//, but any //[[CL:Glossary:object]]// is permitted. However, numbers should not be used because the comparison is done using **[[CL:Functions:eq]]**.

\specref{catch} differs from \specref{block} in that \specref{catch} tags have dynamic //[[CL:Glossary:scope]]// while \specref{block} names have //[[CL:Glossary:lexical scope]]//.


